export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_RECIPE_LIST_REQUEST = 'USER_RECIPE_LIST_REQUEST'
export const USER_RECIPE_LIST_SUCCESS = 'USER_RECIPE_LIST_SUCCESS'
export const USER_RECIPE_LIST_FAIL = 'USER_RECIPE_LIST_FAIL'

export const USER_RECIPE_REMOVE_REQUEST = 'USER_RECIPE_REMOVE_REQUEST'
export const USER_RECIPE_REMOVE_SUCCESS = 'USER_RECIPE_REMOVE_SUCCESS'
export const USER_RECIPE_REMOVE_FAIL = 'USER_RECIPE_REMOVE_FAIL'

export const USER_RECIPE_ADD_REQUEST = 'USER_RECIPE_ADD_REQUEST'
export const USER_RECIPE_ADD_SUCCESS = 'USER_RECIPE_ADD_SUCCESS'
export const USER_RECIPE_ADD_FAIL = 'USER_RECIPE_ADD_FAIL'